### ISSUE TITLE
Production demo rollout TODOs

### ISSUE THREAD

**Issue by keithamoss** [ealgis/ealgis#49]
# TODOs
- [x] [Register an application with Facebook and generate the OAuth2 keys](http://python-social-auth.readthedocs.io/en/latest/backends/facebook.html)
- [x] [Switch DNS to CloudFlare and configure](https://dash.cloudflare.com)
- [x] Have Webpack spit out .js and .css files with hashes in the name so we can use CloudFlare for caching and somehow inject them into `index.prod.html`
- [x] Move `frontend/config.dev.json` to environment variables so we don't need to rebuild the whole image to make small config changes
- [x] [Setup an ealgis.org email account and verify ealgis.org in Mailgun](https://github.com/ealgis/ealgis/issues/149)
- [x] Properly configure `nginx-prod/nginx/conf.d/docker.conf`
- [x] Setup an `ealgis/ealgis-demo` repo
- [x] Spin up DigitalOcean droplets
- [x] Make`build static` pass the "always overwrite" flag so it doesn't try to prompt during `docker-compose up`
- [x] Firewall off the droplet

# Old Stuff
What needs to happen for a PROD rollout:

- **PostgreSQL**
  - See db/postgresql.conf for some defaults
  - http://pgtune.leopard.in.ua/
- **NGinx**
  - Configure 4 subdomains for Vector Tiles in docker.conf to allow the browser to make more than 4 requests to GeoServer at once
- **Django**
  - https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/
- **Google**
  - Set appropriate referrers and origins for both set of credentials on the Google Developers Console
  - Enable the Google Maps JavaScript API and Google Maps Coding API
  - If you get errors about not being authorised for the API, follow the link in the console to https://console.developers.google.com/apis/dashboard?project=PROJECTID to enable the private Google Places API Web Server
- **redux-devtools-extension** https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm

**Comment by grahame** [comment]
releases have been tagged and pushed (2.0.0)

**Comment by grahame** [comment]
```
root@demo:~# mkfs.xfs -f -L docker -n ftype=1 /dev/sda 
meta-data=/dev/sda               isize=512    agcount=4, agsize=3276800 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=0
data     =                       bsize=4096   blocks=13107200, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=6400, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0

```

```
cat >> fstab
LABEL=docker /docker xfs defaults 0 0

root@demo:/etc# mkdir /docker
root@demo:/etc# mount -a

``

**Comment by grahame** [comment]
docker configured to use `/docker` using overlay2 driver - see `/etc/systemd/system/docker.service` and `/etc/docker/daemon.json`

https://docs.docker.com/storage/storagedriver/overlayfs-driver/#configure-docker-with-the-overlay-or-overlay2-storage-driver

**Comment by grahame** [comment]
`apt-get update` `apt-get upgrade` `reboot`

**Comment by keithamoss** [comment]
two issues we might need to ticket up, if you could try to reproduce first
(1) clicking on layers, the highlight seems to have broken (it goes over some other area, like there's some sort of distort on it?)
(2) some of the geometries in australian-electorates don't work, e.g. NT - I don't think that sqrt thing is being built write. also the mvt code shouldn't hard code column names, it should really use those tables instead

**Comment by grahame** [comment]
nice one-liner for data load:
```
bash-4.4# for i in *.dump; do echo "select nspname from pg_catalog.pg_namespace where nspname='"$(basename $i .dump)"';" | psql -U postgres datastore 2>&1 | grep '0 rows' > /dev/null && echo loading: "$i" && pg_restore -U postgres -d datastore < "$i"; done
loading: au_federal_electorate_boundaries.dump
```

**Comment by grahame** [comment]
added some swap

```
root@demo:/# dd if=/dev/zero of=swap.img bs=1M count=4096
4096+0 records in
4096+0 records out
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 5.14751 s, 834 MB/s
root@demo:/# chmod 600 swap.img
root@demo:/# mkswap ./swap.img
Setting up swapspace version 1, size = 4 GiB (4294963200 bytes)
no label, UUID=979db8d4-36e7-436f-8ac4-da5140995a5e
root@demo:/# cd /etc
root@demo:/etc# vi fstab
root@demo:/etc# swapon -a 

```

all the data has now successfully loaded

**Comment by keithamoss** [comment]
For later...think about how we validate that the loaders aren't modifying the data.

One option is just comparing the input (e.g. raw Census CSVs) with the output...but that gets tricky because some CSVs are just loaded as is, others are broken up into multiple tables, yet more are merged into one table.

What other approaches are there?

**Comment by keithamoss** [comment]
http://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/2071.0.55.001~2016~Main%20Features~Commuting%20Distance%20for%20Australia~1

**Comment by keithamoss** [comment]
Fix removing a column when the data browser is open

**Comment by keithamoss** [comment]
Can't scroll the layer sidebar vertically

**Comment by keithamoss** [comment]
Transferred outstanding items to other issues, did the rest.
